"""
FraudMonitor
=============
Watches all agent events in real-time and flags suspicious activity.

Detection Rules:
  - Sandwich attacks (MEV front-run + back-run pattern)
  - Flash loan exploits (borrow → dump → liquidate → repay cycle)
  - Whale manipulation (single trade > X% of pool)
  - Wash trading (circular trades by same entity)
  - Rapid-fire trading (too many txns in short window)
  - Cascade liquidation warnings
"""

import time
from typing import Any, Dict, List, Optional
from dataclasses import dataclass, field
from enum import Enum
from collections import defaultdict


class AlertSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AlertType(str, Enum):
    SANDWICH_ATTACK = "sandwich_attack"
    FLASH_LOAN_EXPLOIT = "flash_loan_exploit"
    WHALE_MANIPULATION = "whale_manipulation"
    WASH_TRADING = "wash_trading"
    RAPID_FIRE = "rapid_fire_trading"
    CASCADE_LIQUIDATION = "cascade_liquidation"
    PRICE_MANIPULATION = "price_manipulation"
    UNUSUAL_SLIPPAGE = "unusual_slippage"


@dataclass
class FraudAlert:
    """A single fraud/risk alert generated by the monitor."""
    id: str
    alert_type: str
    severity: str
    agent_id: str
    agent_type: str
    description: str
    timestamp: float = field(default_factory=time.time)
    data: Dict[str, Any] = field(default_factory=dict)
    resolved: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "type": self.alert_type,
            "severity": self.severity,
            "agent_id": self.agent_id,
            "agent_type": self.agent_type,
            "description": self.description,
            "timestamp": self.timestamp,
            "data": self.data,
            "resolved": self.resolved,
        }


class FraudMonitor:
    """
    Real-time event monitor that applies heuristic rules to detect
    fraud, manipulation, and systemic risk.
    """

    def __init__(self):
        self.alerts: List[FraudAlert] = []
        self.events: List[Dict[str, Any]] = []
        self._alert_counter: int = 0
        self._agent_trade_times: Dict[str, List[float]] = defaultdict(list)
        self._agent_trade_counts: Dict[str, int] = defaultdict(int)

        # Configurable thresholds
        self.whale_threshold_pct: float = 5.0        # single trade > 5% pool
        self.rapid_fire_window: float = 10.0          # seconds
        self.rapid_fire_max_trades: int = 10
        self.slippage_alert_pct: float = 3.0          # slippage > 3%

    def process_event(self, event: Dict[str, Any]):
        """Process an incoming agent event and check all detection rules."""
        self.events.append(event)
        event_type = event.get("event_type", "")
        agent_id = event.get("agent_id", "")
        agent_type = event.get("agent_type", "")
        data = event.get("data", {})
        ts = event.get("timestamp", time.time())

        # Track trade frequency
        self._agent_trade_times[agent_id].append(ts)
        self._agent_trade_counts[agent_id] += 1

        # --- Rule: Sandwich Attack ---
        if event_type == "sandwich_attack":
            self._create_alert(
                AlertType.SANDWICH_ATTACK,
                AlertSeverity.HIGH,
                agent_id,
                agent_type,
                f"Sandwich attack by {event.get('agent_name', agent_id)}: "
                f"front-ran {data.get('victim_id', '?')} for "
                f"${data.get('mev_profit', 0):.2f} profit",
                data,
            )

        # --- Rule: Flash Loan Exploit ---
        if event_type == "flash_loan_attack":
            severity = AlertSeverity.CRITICAL if data.get("liquidations", 0) > 2 else AlertSeverity.HIGH
            self._create_alert(
                AlertType.FLASH_LOAN_EXPLOIT,
                severity,
                agent_id,
                agent_type,
                f"Flash loan attack: ${data.get('flash_amount', 0):,.0f} borrowed, "
                f"{data.get('liquidations', 0)} liquidations triggered, "
                f"${data.get('net_profit', 0):,.2f} profit extracted",
                data,
            )

        # --- Rule: Whale Manipulation ---
        if event_type == "whale_swap":
            pool_impact = data.get("pool_impact_pct", 0)
            if pool_impact > self.whale_threshold_pct:
                self._create_alert(
                    AlertType.WHALE_MANIPULATION,
                    AlertSeverity.HIGH if pool_impact > 8 else AlertSeverity.MEDIUM,
                    agent_id,
                    agent_type,
                    f"Whale trade moved {pool_impact:.1f}% of pool reserves, "
                    f"slippage {data.get('slippage_pct', 0):.2f}%",
                    data,
                )

        # --- Rule: Unusual Slippage ---
        if "receipt" in data:
            slippage = data["receipt"].get("slippage_pct", 0)
            if slippage > self.slippage_alert_pct:
                self._create_alert(
                    AlertType.UNUSUAL_SLIPPAGE,
                    AlertSeverity.MEDIUM,
                    agent_id,
                    agent_type,
                    f"Unusual slippage {slippage:.2f}% on trade by {event.get('agent_name', agent_id)}",
                    {"slippage_pct": slippage, **data},
                )

        # --- Rule: Panic Sell ---
        if event_type == "panic_sell":
            self._create_alert(
                AlertType.PRICE_MANIPULATION,
                AlertSeverity.LOW,
                agent_id,
                agent_type,
                f"Panic sell triggered: price dropped {abs(data.get('price_drop_pct', 0)):.1f}%",
                data,
            )

        # --- Rule: Cascade Liquidations ---
        if event_type == "liquidation_executed":
            # Check if multiple liquidations happening rapidly
            recent_liq_alerts = [
                a for a in self.alerts
                if a.alert_type == AlertType.CASCADE_LIQUIDATION.value
                and time.time() - a.timestamp < 30
            ]
            if len(recent_liq_alerts) >= 2:
                self._create_alert(
                    AlertType.CASCADE_LIQUIDATION,
                    AlertSeverity.CRITICAL,
                    agent_id,
                    agent_type,
                    f"CASCADE WARNING: {len(recent_liq_alerts) + 1} liquidations in rapid succession!",
                    data,
                )
            else:
                self._create_alert(
                    AlertType.CASCADE_LIQUIDATION,
                    AlertSeverity.MEDIUM,
                    agent_id,
                    agent_type,
                    f"Liquidation: {data.get('target', '?')} seized "
                    f"${data.get('seized_collateral', 0):,.2f}",
                    data,
                )

        # --- Rule: Rapid-fire Trading ---
        self._check_rapid_fire(agent_id, agent_type, event.get("agent_name", agent_id), ts)

    def _check_rapid_fire(self, agent_id: str, agent_type: str, agent_name: str, ts: float):
        times = self._agent_trade_times[agent_id]
        # Keep only recent window
        cutoff = ts - self.rapid_fire_window
        recent = [t for t in times if t > cutoff]
        self._agent_trade_times[agent_id] = recent

        if len(recent) > self.rapid_fire_max_trades:
            self._create_alert(
                AlertType.RAPID_FIRE,
                AlertSeverity.MEDIUM,
                agent_id,
                agent_type,
                f"Rapid-fire trading by {agent_name}: "
                f"{len(recent)} trades in {self.rapid_fire_window}s window",
                {"trade_count": len(recent), "window_seconds": self.rapid_fire_window},
            )

    def _create_alert(
        self,
        alert_type: AlertType,
        severity: AlertSeverity,
        agent_id: str,
        agent_type: str,
        description: str,
        data: Dict[str, Any],
    ):
        self._alert_counter += 1
        alert = FraudAlert(
            id=f"alert_{self._alert_counter:04d}",
            alert_type=alert_type.value,
            severity=severity.value,
            agent_id=agent_id,
            agent_type=agent_type,
            description=description,
            data=data,
        )
        self.alerts.append(alert)

    # --- Public query API ---------------------------------------------------

    def get_alerts(
        self,
        severity: Optional[str] = None,
        limit: int = 50,
    ) -> List[Dict[str, Any]]:
        filtered = self.alerts
        if severity:
            filtered = [a for a in filtered if a.severity == severity]
        return [a.to_dict() for a in filtered[-limit:]]

    def get_stats(self) -> Dict[str, Any]:
        by_type = defaultdict(int)
        by_severity = defaultdict(int)
        for a in self.alerts:
            by_type[a.alert_type] += 1
            by_severity[a.severity] += 1

        return {
            "total_alerts": len(self.alerts),
            "total_events": len(self.events),
            "by_type": dict(by_type),
            "by_severity": dict(by_severity),
            "unresolved": sum(1 for a in self.alerts if not a.resolved),
        }

    def get_threat_scores(self) -> List[Dict[str, Any]]:
        """Compute threat radar scores for the frontend."""
        by_type = defaultdict(int)
        for a in self.alerts:
            by_type[a.alert_type] += 1

        total = max(len(self.alerts), 1)

        axes = [
            ("MEV", [AlertType.SANDWICH_ATTACK.value]),
            ("Flash Loan", [AlertType.FLASH_LOAN_EXPLOIT.value]),
            ("Liquidity", [AlertType.WHALE_MANIPULATION.value, AlertType.UNUSUAL_SLIPPAGE.value]),
            ("Cascade", [AlertType.CASCADE_LIQUIDATION.value]),
            ("Price", [AlertType.PRICE_MANIPULATION.value]),
            ("Systemic", [AlertType.RAPID_FIRE.value, AlertType.WASH_TRADING.value]),
        ]

        scores = []
        for axis_name, types in axes:
            count = sum(by_type.get(t, 0) for t in types)
            score = min(int(count / total * 100 * 3), 100) if total > 0 else 0
            status = "safe" if score < 40 else "warning" if score < 70 else "critical"
            scores.append({"axis": axis_name, "score": max(score, 5), "status": status})

        return scores

    def resolve_alert(self, alert_id: str) -> bool:
        for alert in self.alerts:
            if alert.id == alert_id:
                alert.resolved = True
                return True
        return False

    def reset(self):
        self.alerts.clear()
        self.events.clear()
        self._alert_counter = 0
        self._agent_trade_times.clear()
        self._agent_trade_counts.clear()
