"""
FraudMonitor
=============
Watches all agent events in real-time and flags suspicious activity.

Detection Rules:
  - Sandwich attacks (MEV front-run + back-run pattern)
  - Flash loan exploits (borrow → dump → liquidate → repay cycle)
  - Whale manipulation (single trade > X% of pool)
  - Wash trading (circular trades by same entity)
  - Rapid-fire trading (too many txns in short window)
  - Cascade liquidation warnings
  - Oracle manipulation (extreme price divergence)
  - Liquidity poisoning (rapid add/remove at skewed ratios)
  - Coordinated pump-dump (multi-wallet buy burst + large sell)
"""

import asyncio
import time
from typing import Any, Dict, List, Optional, Tuple
from dataclasses import dataclass, field
from enum import Enum
from collections import defaultdict


class AlertSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AlertType(str, Enum):
    SANDWICH_ATTACK = "sandwich_attack"
    FLASH_LOAN_EXPLOIT = "flash_loan_exploit"
    WHALE_MANIPULATION = "whale_manipulation"
    WASH_TRADING = "wash_trading"
    RAPID_FIRE = "rapid_fire_trading"
    CASCADE_LIQUIDATION = "cascade_liquidation"
    PRICE_MANIPULATION = "price_manipulation"
    UNUSUAL_SLIPPAGE = "unusual_slippage"
    ORACLE_MANIPULATION = "oracle_manipulation"
    LIQUIDITY_POISONING = "liquidity_poisoning"
    PUMP_DUMP = "pump_dump"


@dataclass
class FraudAlert:
    """A single fraud/risk alert generated by the monitor."""
    id: str
    alert_type: str
    severity: str
    agent_id: str
    agent_type: str
    description: str
    timestamp: float = field(default_factory=time.time)
    data: Dict[str, Any] = field(default_factory=dict)
    resolved: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "type": self.alert_type,
            "severity": self.severity,
            "agent_id": self.agent_id,
            "agent_type": self.agent_type,
            "description": self.description,
            "timestamp": self.timestamp,
            "data": self.data,
            "resolved": self.resolved,
        }


class FraudMonitor:
    """
    Real-time event monitor that applies heuristic rules to detect
    fraud, manipulation, and systemic risk.
    """

    def __init__(self):
        self.alerts: List[FraudAlert] = []
        self.events: List[Dict[str, Any]] = []
        self._alert_counter: int = 0
        self._agent_trade_times: Dict[str, List[float]] = defaultdict(list)
        self._agent_trade_counts: Dict[str, int] = defaultdict(int)

        # ── Wash-trading state ───────────────────────────────────────
        self._trade_pairs: Dict[Tuple[str, str], List[float]] = defaultdict(list)
        self._wash_window: float = 60.0          # seconds
        self._wash_min_trades: int = 3            # min round-trips to flag

        # ── Oracle manipulation state ────────────────────────────────
        self._price_history: List[Tuple[float, float]] = []   # (ts, price)
        self._oracle_spike_pct: float = 15.0      # single-update spike threshold
        self._oracle_twap_diverge_pct: float = 10.0  # divergence from 20-pt TWAP

        # ── Liquidity poisoning state ────────────────────────────────
        self._liquidity_events: Dict[str, List[Dict]] = defaultdict(list)
        self._poison_window: float = 30.0          # seconds
        self._poison_remove_pct: float = 80.0      # % removed to flag

        # ── Pump-dump state ──────────────────────────────────────────
        self._recent_buys: List[Dict[str, Any]] = []
        self._pump_buy_window: float = 10.0        # seconds for coordinated buys
        self._pump_min_wallets: int = 3            # min distinct buyers
        self._pump_sell_window: float = 30.0       # seconds for the dump

        # Existing thresholds
        self.whale_threshold_pct: float = 5.0      # single trade > 5% pool
        self.rapid_fire_window: float = 10.0       # seconds
        self.rapid_fire_max_trades: int = 10
        self.slippage_alert_pct: float = 3.0       # slippage > 3%

    def process_event(self, event: Dict[str, Any]):
        """Process an incoming agent event and check all detection rules."""
        self.events.append(event)
        event_type = event.get("event_type", "")
        agent_id = event.get("agent_id", "")
        agent_type = event.get("agent_type", "")
        data = event.get("data", {})
        ts = event.get("timestamp", time.time())

        # Track trade frequency
        self._agent_trade_times[agent_id].append(ts)
        self._agent_trade_counts[agent_id] += 1

        # --- Rule: Sandwich Attack ---
        if event_type == "sandwich_attack":
            self._create_alert(
                AlertType.SANDWICH_ATTACK,
                AlertSeverity.HIGH,
                agent_id,
                agent_type,
                f"Sandwich attack by {event.get('agent_name', agent_id)}: "
                f"front-ran {data.get('victim_id', '?')} for "
                f"${data.get('mev_profit', 0):.2f} profit",
                data,
            )

        # --- Rule: Flash Loan Exploit ---
        if event_type == "flash_loan_attack":
            severity = AlertSeverity.CRITICAL if data.get("liquidations", 0) > 2 else AlertSeverity.HIGH
            self._create_alert(
                AlertType.FLASH_LOAN_EXPLOIT,
                severity,
                agent_id,
                agent_type,
                f"Flash loan attack: ${data.get('flash_amount', 0):,.0f} borrowed, "
                f"{data.get('liquidations', 0)} liquidations triggered, "
                f"${data.get('net_profit', 0):,.2f} profit extracted",
                data,
            )

        # --- Rule: Whale Manipulation ---
        if event_type == "whale_swap":
            pool_impact = data.get("pool_impact_pct", 0)
            if pool_impact > self.whale_threshold_pct:
                self._create_alert(
                    AlertType.WHALE_MANIPULATION,
                    AlertSeverity.HIGH if pool_impact > 8 else AlertSeverity.MEDIUM,
                    agent_id,
                    agent_type,
                    f"Whale trade moved {pool_impact:.1f}% of pool reserves, "
                    f"slippage {data.get('slippage_pct', 0):.2f}%",
                    data,
                )

        # --- Rule: Unusual Slippage ---
        if "receipt" in data:
            slippage = data["receipt"].get("slippage_pct", 0)
            if slippage > self.slippage_alert_pct:
                self._create_alert(
                    AlertType.UNUSUAL_SLIPPAGE,
                    AlertSeverity.MEDIUM,
                    agent_id,
                    agent_type,
                    f"Unusual slippage {slippage:.2f}% on trade by {event.get('agent_name', agent_id)}",
                    {"slippage_pct": slippage, **data},
                )

        # --- Rule: Panic Sell ---
        if event_type == "panic_sell":
            self._create_alert(
                AlertType.PRICE_MANIPULATION,
                AlertSeverity.LOW,
                agent_id,
                agent_type,
                f"Panic sell triggered: price dropped {abs(data.get('price_drop_pct', 0)):.1f}%",
                data,
            )

        # --- Rule: Cascade Liquidations ---
        if event_type == "liquidation_executed":
            recent_liq_alerts = [
                a for a in self.alerts
                if a.alert_type == AlertType.CASCADE_LIQUIDATION.value
                and time.time() - a.timestamp < 30
            ]
            if len(recent_liq_alerts) >= 2:
                self._create_alert(
                    AlertType.CASCADE_LIQUIDATION,
                    AlertSeverity.CRITICAL,
                    agent_id,
                    agent_type,
                    f"CASCADE WARNING: {len(recent_liq_alerts) + 1} liquidations in rapid succession!",
                    data,
                )
            else:
                self._create_alert(
                    AlertType.CASCADE_LIQUIDATION,
                    AlertSeverity.MEDIUM,
                    agent_id,
                    agent_type,
                    f"Liquidation: {data.get('target', '?')} seized "
                    f"${data.get('seized_collateral', 0):,.2f}",
                    data,
                )

        # --- Rule: Wash Trading ---
        if event_type in ("swap", "trade", "wash_trade"):
            self._check_wash_trading(agent_id, agent_type, data, ts)

        # --- Rule: Oracle Manipulation ---
        if event_type in ("price_update", "oracle_update", "oracle_manipulation"):
            self._check_oracle_manipulation(agent_id, agent_type, data, ts)

        # --- Rule: Liquidity Poisoning ---
        if event_type in ("add_liquidity", "remove_liquidity", "liquidity_poison"):
            self._check_liquidity_poisoning(agent_id, agent_type, event_type, data, ts)

        # --- Rule: Pump & Dump ---
        if event_type in ("buy", "sell", "swap", "trade", "pump_buy", "pump_sell"):
            self._check_pump_dump(agent_id, agent_type, event_type, data, ts)

        # --- Rule: Rapid-fire Trading ---
        self._check_rapid_fire(agent_id, agent_type, event.get("agent_name", agent_id), ts)

    # =====================================================================
    # WASH TRADING DETECTOR
    # =====================================================================
    def _check_wash_trading(self, agent_id: str, agent_type: str, data: Dict, ts: float):
        """Detect circular trades: same wallet pair trading back-and-forth."""
        counterparty = data.get("counterparty", data.get("receiver", ""))
        if not counterparty or counterparty == agent_id:
            return

        pair = tuple(sorted([agent_id, counterparty]))
        self._trade_pairs[pair].append(ts)

        # Prune old entries
        cutoff = ts - self._wash_window
        self._trade_pairs[pair] = [t for t in self._trade_pairs[pair] if t > cutoff]

        count = len(self._trade_pairs[pair])
        if count >= self._wash_min_trades:
            volume = data.get("amount", 0) * count
            self._create_alert(
                AlertType.WASH_TRADING,
                AlertSeverity.HIGH if count >= 5 else AlertSeverity.MEDIUM,
                agent_id,
                agent_type,
                f"Wash trading detected: {count} round-trip trades between "
                f"{agent_id[:10]}… and {counterparty[:10]}… in {self._wash_window}s "
                f"(~${volume:,.0f} inflated volume)",
                {
                    "trade_count": count,
                    "pair": list(pair),
                    "window_seconds": self._wash_window,
                    "estimated_inflated_volume": round(volume, 2),
                },
            )

    # =====================================================================
    # ORACLE MANIPULATION DETECTOR
    # =====================================================================
    def _check_oracle_manipulation(self, agent_id: str, agent_type: str, data: Dict, ts: float):
        """Detect abnormal price feed updates — spikes or TWAP divergence."""
        price = data.get("price", data.get("new_price", 0))
        if price <= 0:
            return

        self._price_history.append((ts, price))

        # Keep rolling window of last 50 updates
        if len(self._price_history) > 50:
            self._price_history = self._price_history[-50:]

        if len(self._price_history) < 2:
            return

        prev_price = self._price_history[-2][1]
        change_pct = abs(price - prev_price) / prev_price * 100

        # Check single-update spike
        if change_pct > self._oracle_spike_pct:
            self._create_alert(
                AlertType.ORACLE_MANIPULATION,
                AlertSeverity.CRITICAL,
                agent_id,
                agent_type,
                f"Oracle price spike: {change_pct:.1f}% change in single update "
                f"(${prev_price:,.2f} → ${price:,.2f}). "
                f"Possible Mango Markets-style oracle manipulation.",
                {
                    "price_before": round(prev_price, 4),
                    "price_after": round(price, 4),
                    "change_pct": round(change_pct, 2),
                    "detection_method": "single_update_spike",
                },
            )

        # Check TWAP divergence (use last 20 points)
        if len(self._price_history) >= 5:
            recent = self._price_history[-20:]
            twap = sum(p for _, p in recent) / len(recent)
            divergence_pct = abs(price - twap) / twap * 100

            if divergence_pct > self._oracle_twap_diverge_pct:
                self._create_alert(
                    AlertType.ORACLE_MANIPULATION,
                    AlertSeverity.HIGH,
                    agent_id,
                    agent_type,
                    f"Oracle TWAP divergence: current ${price:,.2f} is "
                    f"{divergence_pct:.1f}% away from TWAP ${twap:,.2f}. "
                    f"Potential price feed manipulation.",
                    {
                        "current_price": round(price, 4),
                        "twap": round(twap, 4),
                        "divergence_pct": round(divergence_pct, 2),
                        "twap_window": len(recent),
                        "detection_method": "twap_divergence",
                    },
                )

    # =====================================================================
    # LIQUIDITY POISONING DETECTOR
    # =====================================================================
    def _check_liquidity_poisoning(
        self, agent_id: str, agent_type: str, event_type: str, data: Dict, ts: float
    ):
        """Detect rapid add+remove liquidity patterns at skewed ratios."""
        self._liquidity_events[agent_id].append({
            "type": event_type,
            "ts": ts,
            "amount": data.get("amount", data.get("shares", 0)),
            "amount_a": data.get("amount_a", 0),
            "amount_b": data.get("amount_b", 0),
        })

        # Prune old
        cutoff = ts - self._poison_window
        self._liquidity_events[agent_id] = [
            e for e in self._liquidity_events[agent_id] if e["ts"] > cutoff
        ]

        events = self._liquidity_events[agent_id]
        adds = [e for e in events if "add" in e["type"]]
        removes = [e for e in events if "remove" in e["type"]]

        if adds and removes:
            total_added = sum(e["amount"] for e in adds)
            total_removed = sum(e["amount"] for e in removes)

            if total_added > 0:
                remove_ratio = (total_removed / total_added) * 100
                if remove_ratio >= self._poison_remove_pct:
                    time_delta = removes[-1]["ts"] - adds[0]["ts"]
                    self._create_alert(
                        AlertType.LIQUIDITY_POISONING,
                        AlertSeverity.HIGH,
                        agent_id,
                        agent_type,
                        f"Liquidity poisoning: {agent_id[:10]}… added then removed "
                        f"{remove_ratio:.0f}% of liquidity within {time_delta:.1f}s. "
                        f"Likely price/ratio manipulation attempt.",
                        {
                            "total_added": round(total_added, 2),
                            "total_removed": round(total_removed, 2),
                            "remove_ratio_pct": round(remove_ratio, 1),
                            "time_delta_seconds": round(time_delta, 1),
                            "add_events": len(adds),
                            "remove_events": len(removes),
                        },
                    )

    # =====================================================================
    # PUMP & DUMP DETECTOR
    # =====================================================================
    def _check_pump_dump(
        self, agent_id: str, agent_type: str, event_type: str, data: Dict, ts: float
    ):
        """Detect coordinated buy burst followed by a single large sell."""
        is_buy = event_type in ("buy", "pump_buy") or data.get("side") == "buy"
        is_sell = event_type in ("sell", "pump_sell") or data.get("side") == "sell"
        amount = data.get("amount", 0)

        if is_buy:
            self._recent_buys.append({
                "wallet": agent_id,
                "ts": ts,
                "amount": amount,
            })
            # Prune old buys
            cutoff = ts - self._pump_sell_window
            self._recent_buys = [b for b in self._recent_buys if b["ts"] > cutoff]

        if is_sell and amount > 0:
            # Check if there was a coordinated buy burst before this sell
            buy_cutoff = ts - self._pump_sell_window
            recent = [b for b in self._recent_buys if b["ts"] > buy_cutoff]
            distinct_wallets = set(b["wallet"] for b in recent)

            # Remove seller from buyer set (the dumper may have also bought)
            if agent_id in distinct_wallets:
                distinct_wallets.discard(agent_id)

            if len(distinct_wallets) >= self._pump_min_wallets:
                total_buy_volume = sum(b["amount"] for b in recent)
                self._create_alert(
                    AlertType.PUMP_DUMP,
                    AlertSeverity.CRITICAL,
                    agent_id,
                    agent_type,
                    f"Coordinated pump & dump detected! "
                    f"{len(distinct_wallets)} wallets bought ${total_buy_volume:,.0f} "
                    f"then {agent_id[:10]}… dumped ${amount:,.0f}. "
                    f"Classic pump-dump pattern.",
                    {
                        "dump_wallet": agent_id,
                        "dump_amount": round(amount, 2),
                        "pump_wallets": list(distinct_wallets),
                        "pump_wallet_count": len(distinct_wallets),
                        "total_buy_volume": round(total_buy_volume, 2),
                        "window_seconds": self._pump_sell_window,
                    },
                )
                # Clear to avoid duplicate alerts
                self._recent_buys.clear()

    # =====================================================================
    # RAPID-FIRE TRADING DETECTOR (existing)
    # =====================================================================
    def _check_rapid_fire(self, agent_id: str, agent_type: str, agent_name: str, ts: float):
        times = self._agent_trade_times[agent_id]
        cutoff = ts - self.rapid_fire_window
        recent = [t for t in times if t > cutoff]
        self._agent_trade_times[agent_id] = recent

        if len(recent) > self.rapid_fire_max_trades:
            self._create_alert(
                AlertType.RAPID_FIRE,
                AlertSeverity.MEDIUM,
                agent_id,
                agent_type,
                f"Rapid-fire trading by {agent_name}: "
                f"{len(recent)} trades in {self.rapid_fire_window}s window",
                {"trade_count": len(recent), "window_seconds": self.rapid_fire_window},
            )

    # =====================================================================
    # ALERT CREATION
    # =====================================================================
    def _create_alert(
        self,
        alert_type: AlertType,
        severity: AlertSeverity,
        agent_id: str,
        agent_type: str,
        description: str,
        data: Dict[str, Any],
    ):
        self._alert_counter += 1
        alert = FraudAlert(
            id=f"alert_{self._alert_counter:04d}",
            alert_type=alert_type.value,
            severity=severity.value,
            agent_id=agent_id,
            agent_type=agent_type,
            description=description,
            data=data,
        )
        self.alerts.append(alert)

        # ── Groq AI analysis  + email notification for HIGH/CRITICAL ──
        if severity in (AlertSeverity.HIGH, AlertSeverity.CRITICAL):
            self._dispatch_groq_and_email(alert)

    def _dispatch_groq_and_email(self, alert: FraudAlert):
        """Fire-and-forget Groq analysis + email dispatch for severe alerts."""
        try:
            loop = asyncio.get_event_loop()
            if loop.is_running():
                loop.create_task(self._async_groq_and_email(alert))
            else:
                # Not inside an async context — skip
                pass
        except RuntimeError:
            pass  # no event loop

    async def _async_groq_and_email(self, alert: FraudAlert):
        """Run Groq threat analysis, attach result to alert, send email."""
        groq_analysis = None
        try:
            from agents.groq_advisor import analyze_threat
            # Build a mini event list from this alert for Groq
            events = [{
                "event_type": alert.alert_type,
                "agent_id": alert.agent_id,
                "agent_type": alert.agent_type,
                "description": alert.description,
                "data": alert.data,
                "timestamp": alert.timestamp,
            }]
            # Also include last 5 events for context
            context_events = self.events[-5:] if self.events else []
            groq_analysis = await analyze_threat(events + context_events, {})
            if groq_analysis:
                alert.data["groq_analysis"] = groq_analysis
        except Exception as e:
            print(f"⚠️  Groq threat analysis failed for {alert.id}: {e}")

        # Send email
        try:
            from email_service import send_threat_alert_email
            alert_dict = alert.to_dict()
            import datetime
            alert_dict["timestamp"] = datetime.datetime.fromtimestamp(
                alert.timestamp
            ).strftime("%Y-%m-%d %H:%M:%S UTC")
            await send_threat_alert_email(alert_dict, groq_analysis)
        except Exception as e:
            print(f"⚠️  Email dispatch failed for {alert.id}: {e}")

    # --- Public query API -------------------------------------------------

    def get_alerts(
        self,
        severity: Optional[str] = None,
        limit: int = 50,
    ) -> List[Dict[str, Any]]:
        filtered = self.alerts
        if severity:
            filtered = [a for a in filtered if a.severity == severity]
        return [a.to_dict() for a in filtered[-limit:]]

    def get_stats(self) -> Dict[str, Any]:
        by_type = defaultdict(int)
        by_severity = defaultdict(int)
        for a in self.alerts:
            by_type[a.alert_type] += 1
            by_severity[a.severity] += 1

        return {
            "total_alerts": len(self.alerts),
            "total_events": len(self.events),
            "by_type": dict(by_type),
            "by_severity": dict(by_severity),
            "unresolved": sum(1 for a in self.alerts if not a.resolved),
        }

    def get_threat_scores(self) -> List[Dict[str, Any]]:
        """Compute threat radar scores for the frontend."""
        by_type = defaultdict(int)
        for a in self.alerts:
            by_type[a.alert_type] += 1

        total = max(len(self.alerts), 1)

        axes = [
            ("MEV", [AlertType.SANDWICH_ATTACK.value]),
            ("Flash Loan", [AlertType.FLASH_LOAN_EXPLOIT.value]),
            ("Wash Trade", [AlertType.WASH_TRADING.value]),
            ("Oracle", [AlertType.ORACLE_MANIPULATION.value]),
            ("Liquidity", [AlertType.WHALE_MANIPULATION.value, AlertType.UNUSUAL_SLIPPAGE.value, AlertType.LIQUIDITY_POISONING.value]),
            ("Pump-Dump", [AlertType.PUMP_DUMP.value]),
            ("Cascade", [AlertType.CASCADE_LIQUIDATION.value]),
        ]

        scores = []
        for axis_name, types in axes:
            count = sum(by_type.get(t, 0) for t in types)
            score = min(int(count / total * 100 * 3), 100) if total > 0 else 0
            status = "safe" if score < 40 else "warning" if score < 70 else "critical"
            scores.append({"axis": axis_name, "score": max(score, 5), "status": status})

        return scores

    def resolve_alert(self, alert_id: str) -> bool:
        for alert in self.alerts:
            if alert.id == alert_id:
                alert.resolved = True
                return True
        return False

    def reset(self):
        self.alerts.clear()
        self.events.clear()
        self._alert_counter = 0
        self._agent_trade_times.clear()
        self._agent_trade_counts.clear()
        self._trade_pairs.clear()
        self._price_history.clear()
        self._liquidity_events.clear()
        self._recent_buys.clear()
